version: "3"

services:
    sql:
        container_name: sql
        # restart: always
        image: postgres:latest
        volumes:
            # - ./sql/data:/var/lib/postgresql/data
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_PASSWORD=n0blog
            - POSTGRES_USER=n0blog
    redis:
        container_name: redis
        image: redis:latest
    n0blog:
        container_name: n0blog
        build: ./python
        depends_on:
            - sql
        volumes:
            - ./python/app:/home/n0blog/app
              #- ./python/migrations:/home/n0blog/migrations
            - ./posts:/posts
        ports:
            - 8000:5000
        environment:
            - DEV_DATABASE_URL=postgresql://n0blog:n0blog@sql/n0blog
            - TEST_DATABASE_URL=postgresql://n0blog:n0blog@sql/n0blog
            - DATABASE_URL=postgresql://n0blog:n0blog@sql/n0blog
            - PGPASSWORD=n0blog
            - REDIS_URL=redis://redis/0
            - SECRET_KEY=n0blog
            - FLASK_APP=n0blog
            - ADMIN_PASS=n0blog
